Task1
kpilyugin/softwaredesign pull request #1
Opened 2016-09-22 21:50 UTC by kpilyugin

2016-09-26 04:36 UTC, yurii-litvinov commented on shell/src/main/java/ru/spbau/mit/repl/shell/ShellVariables.java
> +
стайлгайды обычно не поощряют две пустые строки подряд

2016-09-26 04:38 UTC, yurii-litvinov commented on shell/src/main/java/ru/spbau/mit/repl/util/Parser.java
> +   * @param command       text command from input
выравнивать пробелами плохо, потому что усложняет рефакторинг --- после переименования переменной надо перевыровнять всё, что, во-первых, лишняя работа, во-вторых, портит диффы

2016-09-26 04:41 UTC, yurii-litvinov requested changes
- тесты хрупкие, под виндой у меня ни один тест на команды не прошёл (из-за проблем с CR LF и путями). Впрочем, для прототипа это ок, можно не править.
- x=echo
  $x 1
  выдаёт
  Failed to execute command: 
  java.io.IOException: Cannot run program "$x": CreateProcess error=2, Не удается найти указанный файл
- ещё нужен краткий текст с архитектурным описанием

2016-09-26 20:59 UTC, kpilyugin commented on shell/src/main/java/ru/spbau/mit/repl/util/Parser.java
> +   * @param command       text command from input
идея почему-то по дефолту именно так и выравнивает в javadoc

2016-09-26 22:26 UTC, kpilyugin commented
@yurii-litvinov поправил замечания

2016-12-04 20:19 UTC, yurii-litvinov approved these changes

2016-12-04 20:19 UTC, merged